version: "3.4"

volumes:
    carceropolis_db:
    carceropolis_static:
    carceropolis_media:
    carceropolis_sockets:

services:
    memcached:
        image: memcached:1.5-alpine

    db:
        image: postgres:10.2-alpine
        environment:
            - POSTGRES_DB=${DB_NAME:-postgres}
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_PASSWORD=${DB_PASS:-carceropolis}
            # - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - carceropolis_db:/var/lib/postgresql/data

    nginx:
        image: nginx:1.13-alpine
        volumes:
            - carceropolis_static:/project/carceropolis/static
            - carceropolis_media:/project/carceropolis/static/media
            - carceropolis_sockets:/sockets
            - ./deploy:/project/deploy
            - ./deploy/nginx:/etc/nginx/conf.d
            - ./letsencrypt:/letsencrypt:ro
            - ./logs:/logs
        ports:
            - "80:80"
            - "443:443"

    carceropolis:
        image: askbr/carceropolis
        build: .
        environment:
            # This options are used on settings.py
            - DEBUG=${DEBUG:-True}  # Default to True
            - IS_PRODUCTION=${IS_PRODUCTION}  # Default to empty
            - CONSOLE_LOG_LEVEL=${CONSOLE_LOG_LEVEL:-DEBUG}  # Default to DEBUG
            - SECRET_KEY=${SECRET_KEY}
            - NEVERCACHE_KEY=${NEVERCACHE_KEY}
            - DB_NAME=${DB_NAME:-postgres}
            - DB_USER=${DB_USER:-postgres}
            - DB_PASS=${DB_PASS:-carceropolis}
            - DB_HOST=${DB_HOST:-db}
            - DB_PORT=${DB_PORT:-5432}
            - PUBLICACAO_PER_PAGE=${PUBLICACAO_PER_PAGE:-9}  # Default to 9
            - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-50MB}  # Default to 50MB
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - EMAIL_PORT=${EMAIL_PORT:-465}
            - EMAIL_USE_TLS=${EMAIL_USE_TLS:-False}
            - EMAIL_USE_SSL=${EMAIL_USE_SSL:-True}
        volumes:
            - .:/project
            - carceropolis_sockets:/sockets
            - carceropolis_static:/project/carceropolis/static
            - carceropolis_media:/project/carceropolis/static/media
        ports:
            - "5006:5006"
        links:
            - db
            - nginx
            - memcached
        depends_on:
            - db
            - nginx
            - memcached
