version: "3"

volumes:
    carceropolis_db:
    carceropolis_media:

services:
    db:
        image: postgres:10.2-alpine
        environment:
            - POSTGRES_NAME=${DB_NAME:-postgres}
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_PASSWORD=${DB_PASS:-carceropolis}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - carceropolis_db:/var/lib/postgresql/data/pgdata

    memcached:
        image: memcached:1.5-alpine

    web:
        build: .
        image: askbr/carceropolis
        environment:
            - DEBUG=${DEBUG}  # Default to True
            - IS_PRODUCTION=${IS_PRODUCTION}  # Default to empty
            - CONSOLE_LOG_LEVEL=${CONSOLE_LOG_LEVEL}  # Default to DEBUG
            - SECRET_KEY=${SECRET_KEY}
            - NEVERCACHE_KEY=${NEVERCACHE_KEY}
            - DB_NAME=${DB_NAME:-postgres}
            - DB_USER=${DB_USER:-postgres}
            - DB_PASS=${DB_PASS:-carceropolis}
            - DB_HOST=${DB_HOST:-db}
            - PUBLICACAO_PER_PAGE=${PUBLICACAO_PER_PAGE}
            - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
        volumes:
            - ./carceropolis:/project
            - carceropolis_media:/project/static/media
        ports:
            - "8000:8000"
            - "5006:5006"
        links:
            - db
            - memcached
        depends_on:
            - db
            - memcached
            - migrate
        command: >
            sh -c "python manage.py makemigrations &&
            python manage.py migrate --no-input &&
            python manage.py collectstatic --no-input &&
            python manage.py runserver 0.0.0.0:8000"

    loaddata:
        image: askbr/carceropolis
        volumes:
            - ./carceropolis:/project
            - carceropolis_media:/project/static/media
        links:
            - db
        depends_on:
            - db
            - migrate
        command: python3 manage.py loaddata cidades/fixtures/cidade.json.bz2 carceropolis/fixtures/initialdata.json.bz2

    migrate:
        image: askbr/carceropolis
        volumes:
            - ./carceropolis:/project
            - carceropolis_media:/project/static/media
        links:
            - db
        depends_on:
            - db
        command: sh -c "python manage.py makemigrations && python manage.py migrate --no-input"
