version: "3"

services:
    db:
        restart: always
        image: postgres
        ports:
            - "5432:5432"
    memcached:
        restart: always
        image: memcached
        ports:
            - "11211:11211"
    web:
        restart: always
        build: .
        image: carceropolis
        links:
            - db
            - memcached
        command: >
            bash -c "python manage.py makemigrations &&
            python manage.py migrate --no-input &&
            python manage.py collectstatic --no-input &&
            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/project
        ports:
            - "8000:8000"
            - "5006:5006"
        depends_on:
            - db
            - memcached
            - migrate
    loaddata:
        image: carceropolis
        links:
            - db
            - memcached
        volumes:
            - .:/project
        command: python3 manage.py loaddata cidades/fixtures/cidade.json.bz2 carceropolis/fixtures/initialdata.json.bz2
        depends_on:
            - db
            - memcached
            - migrate
    migrate:
        image: carceropolis
        links:
            - db
            - memcached
        volumes:
            - .:/project
        command: bash -c "python manage.py makemigrations && python manage.py migrate"
        depends_on:
            - db
            - memcached
